// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXIOtvD_AF77OORdpDfh8tP54N-G6yhN8',
    appId: '1:151269928534:web:c2f6b918a513e35a8f95f7',
    messagingSenderId: '151269928534',
    projectId: 'final-project-sce',
    authDomain: 'final-project-sce.firebaseapp.com',
    storageBucket: 'final-project-sce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvOiUzTS4b7YZhL_vUd25yv9kx4WkNLWE',
    appId: '1:151269928534:android:cd755a9ecbca05828f95f7',
    messagingSenderId: '151269928534',
    projectId: 'final-project-sce',
    storageBucket: 'final-project-sce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK9W8bYluFaCE6NCNlciLj_ABiDal-HMQ',
    appId: '1:151269928534:ios:da6159c636006fa68f95f7',
    messagingSenderId: '151269928534',
    projectId: 'final-project-sce',
    storageBucket: 'final-project-sce.appspot.com',
    iosBundleId: 'com.example.finalProjectSce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK9W8bYluFaCE6NCNlciLj_ABiDal-HMQ',
    appId: '1:151269928534:ios:8c8318006d38488e8f95f7',
    messagingSenderId: '151269928534',
    projectId: 'final-project-sce',
    storageBucket: 'final-project-sce.appspot.com',
    iosBundleId: 'com.example.finalProjectSce.RunnerTests',
  );
}
